### PR TITLE
Calculation functions

### PR DESCRIPTION
**Pull request by EphraimB**

### CODE REVIEW

**Review by sherzberg — CHANGES_REQUESTED** [review]
Please add test tables for several different cases for each test to practice using them.

**Comment by EphraimB** [comment]
> Please add test tables for several different cases for each test to practice using them.

In addition to the tests I already have?

**Comment by sherzberg** [comment]
@EphraimB can you move these files into the `go-testing-tutorial` folder?

**Comment by EphraimB** [comment]
> @EphraimB can you move these files into the `go-testing-tutorial` folder?

Why? It's not part of the tutorial.

**Review by sherzberg — APPROVED** [review]

**Pull request merged**
